[[headers]]
  for = "index.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    cache-control: max-age=0
    cache-control: no-cache
    cache-control: no-store
    cache-control: must-revalidate
    
